# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(blank=True, default='Peon', max_length=32),
        ),
    ]
